// Package config loads and saves the .ainow/config.yaml file that steers
// scanning, planning and card generation for a target repository.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// Dir is the name of the knowledge directory created inside a target repo.
const Dir = ".kaioken"

// Config is the user-editable configuration for one target repository.
type Config struct {
	Version int `yaml:"version"`
	// Model is a model id, e.g. "anthropic/claude-sonnet-4.5".
	Model string `yaml:"model"`
	// Provider names an entry in llm.Providers (openrouter, openai, groq, …).
	Provider string `yaml:"provider"`
	// BaseURL, when non-empty, overrides the provider's default endpoint
	// (useful for self-hosted / OpenAI-compatible gateways).
	BaseURL string `yaml:"base_url"`
	// Concurrency is the number of modules generated in parallel.
	Concurrency int `yaml:"concurrency"`
	// MaxModuleTokens caps the source context bundled per module (approx tokens).
	MaxModuleTokens int `yaml:"max_module_tokens"`
	// MaxTokens caps the reply length. It is a spending control as much as a
	// length one: providers reserve credit for the full ceiling before running
	// the request, so an unset cap can make a large-context model unaffordable
	// even when every reply is short. Zero falls back to llm.DefaultMaxTokens.
	MaxTokens int   `yaml:"max_tokens,omitempty"`
	Scope     Scope `yaml:"scope"`
	// Notes are steering instructions injected verbatim into every LLM prompt.
	// This is the human-in-the-loop channel: conventions the code alone does
	// not state, warnings, and "do not do X" guardrails.
	Notes []string `yaml:"notes"`
	// Memory controls the agent's experience loop: the project memory file,
	// session digests, and skill distillation. Zero values are safe — memory
	// is opt-in and degrades to "explicit /learn only".
	Memory Memory `yaml:"memory,omitempty"`
	// Budget sets proactive USD spending guardrails for agent sessions. Zero
	// values disable them. Spend is only known when the provider reports it
	// (OpenRouter does); elsewhere the guardrails stay inert.
	Budget Budget `yaml:"budget,omitempty"`
}

// Budget is the per-session spending guardrail. Both thresholds are USD;
// zero disables the threshold.
type Budget struct {
	// WarnAt injects a one-time warning into the conversation once the
	// session's spend passes this amount.
	WarnAt float64 `yaml:"warn_at,omitempty"`
	// HardStop refuses further LLM calls once the session's spend reaches
	// this amount, telling the user how to proceed.
	HardStop float64 `yaml:"hard_stop,omitempty"`
}

// Memory configures the agent's persistent learning. It maps the wiki depth
// multiplier onto learning aggressiveness with one knob: ×1 (default) means an
// explicit /learn is the only trigger; ×5 also distills at session end; ×10
// also reviews each turn, Hermes-style.
type Memory struct {
	// Learn is the aggressiveness multiplier (1, 5, or 10). 0 behaves as 1.
	Learn int `yaml:"learn,omitempty"`
	// Disable turns the whole loop off, including the remember/recall tools.
	// Project memory already on disk still reaches the prompt.
	Disable bool `yaml:"disable,omitempty"`
	// MaxSkills caps how many learned skills the catalog keeps before pruning
	// the least-reinforced. Zero means no explicit cap (decay still flags).
	MaxSkills int `yaml:"max_skills,omitempty"`
}

// LearnThreshold returns the configured learn multiplier, floored to 1.
func (c *Config) LearnThreshold() int {
	if c == nil {
		return 1
	}
	if c.Memory.Learn < 1 {
		return 1
	}
	return c.Memory.Learn
}

// LearnAtSessionEnd reports whether distillation should run when a session ends.
func (c *Config) LearnAtSessionEnd() bool { return !c.Memory.Disable && c.LearnThreshold() >= 5 }

// LearnPerTurn reports whether distillation should run after every turn.
func (c *Config) LearnPerTurn() bool { return !c.Memory.Disable && c.LearnThreshold() >= 10 }

// Scope controls which files are considered part of the repository.
type Scope struct {
	// Include, when non-empty, restricts scanning to these path prefixes.
	Include []string `yaml:"include"`
	// Exclude lists path globs/prefixes skipped in addition to .gitignore.
	Exclude []string `yaml:"exclude"`
}

// DefaultExcludes are always skipped regardless of configuration. Dir itself
// is listed: without it Kaioken scans its own generated wiki and cards as if
// they were source, inflating every prompt and polluting the plan. (".ainow"
// is the pre-rename name, kept so repos generated by older builds stay clean.)
var DefaultExcludes = []string{
	".git", Dir, ".ainow", ".qoder", "node_modules", "dist", "build", "out",
	".venv", "venv", "__pycache__", ".ruff_cache", ".pytest_cache",
	".mypy_cache", ".next", ".nuxt", "target", "vendor", "coverage",
	".idea", ".vscode", ".DS_Store",
}

// Default returns a fresh config with sensible defaults.
func Default() *Config {
	return &Config{
		Version:         1,
		Model:           "nvidia/nemotron-3-ultra-550b-a55b:free",
		Provider:        "openrouter",
		Concurrency:     4,
		MaxModuleTokens: 60000,
		Scope: Scope{
			Exclude: []string{
				"**/*.lock", "**/pnpm-lock.yaml", "**/package-lock.json",
				"**/uv.lock", "**/*.min.js", "**/*.map",
			},
		},
		Notes: []string{},
	}
}

// FreeModelConcurrency caps parallel requests against a provider's free tier.
const FreeModelConcurrency = 2

// IsFreeModel reports whether a model id names a provider's free tier, which
// OpenRouter and others mark with a ":free" suffix.
func IsFreeModel(model string) bool {
	return strings.HasSuffix(strings.ToLower(strings.TrimSpace(model)), ":free")
}

// EffectiveConcurrency is the parallelism to actually use for a model. Free
// tiers enforce tight per-minute limits, so fanning out the configured four
// requests at once mostly buys 429s and backoff — those get capped instead.
// Returns the limit and whether it was clamped, so callers can say so.
func (c *Config) EffectiveConcurrency(model string) (limit int, clamped bool) {
	n := c.Concurrency
	if n < 1 {
		n = 1
	}
	if IsFreeModel(model) && n > FreeModelConcurrency {
		return FreeModelConcurrency, true
	}
	return n, false
}

// Path returns the config file path for a repo root.
func Path(repo string) string {
	return filepath.Join(repo, Dir, "config.yaml")
}

// Load reads the config for a repo, returning a helpful error if missing.
func Load(repo string) (*Config, error) {
	raw, err := os.ReadFile(Path(repo))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no %s/config.yaml found in %s — run `kaioken init` first", Dir, repo)
		}
		return nil, err
	}
	cfg := Default()
	if err := yaml.Unmarshal(raw, cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", Path(repo), err)
	}
	if cfg.Concurrency < 1 {
		cfg.Concurrency = 1
	}
	if cfg.MaxModuleTokens < 4000 {
		cfg.MaxModuleTokens = 4000
	}
	return cfg, nil
}

// Save writes the config, creating the .ainow directory if needed.
func (c *Config) Save(repo string) error {
	if err := os.MkdirAll(filepath.Join(repo, Dir), 0o755); err != nil {
		return err
	}
	raw, err := yaml.Marshal(c)
	if err != nil {
		return err
	}
	header := []byte("# ainow configuration — edit freely.\n" +
		"# `notes` are injected into every generation prompt: use them to teach\n" +
		"# the model conventions, guardrails, and tribal knowledge.\n")
	return os.WriteFile(Path(repo), append(header, raw...), 0o644)
}
