// Package onboard turns Kaioken's generated knowledge into a single document
// a new team member can follow on day one. Everything it writes is derived
// from artifacts already on disk — wiki chapters, knowledge cards, skills and
// the scan inventory — so it needs no LLM call and can never invent facts.
package onboard

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"kaioken/internal/config"
	"kaioken/internal/scan"
	"kaioken/internal/skills"
)

// leadChapters are the wiki sections a newcomer should read first, in order.
// Any that do not exist are silently skipped — a half-generated wiki still
// yields a useful guide.
var leadChapters = []string{"Getting Started", "Architecture Overview", "Development Guide"}

// maxIntroRunes caps how much of the wiki README leads the document.
const maxIntroRunes = 600

// Generate builds the ONBOARDING.md body for repo.
func Generate(repo string, cfg *config.Config) (string, error) {
	var b strings.Builder
	name := filepath.Base(repo)
	if abs, err := filepath.Abs(repo); err == nil {
		name = filepath.Base(abs)
	}
	fmt.Fprintf(&b, "# Onboarding — %s\n\n", name)
	fmt.Fprintf(&b, "Generated by Kaioken from the repository's own knowledge base. "+
		"If something below looks stale, run `kaioken update` and regenerate.\n\n")

	wikiDir := filepath.Join(repo, config.Dir, "wiki")

	// 1. What this repo is — the wiki README's opening, when one exists.
	if intro := readIntro(wikiDir); intro != "" {
		b.WriteString(intro + "\n\n")
	}

	// 2. Read these first — the canonical entry-point chapters.
	b.WriteString("## Read these first\n\n")
	linked := 0
	for _, chapter := range leadChapters {
		dir := filepath.Join(wikiDir, chapter)
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			title := strings.TrimSuffix(e.Name(), ".md")
			rel := filepath.ToSlash(filepath.Join(config.Dir, "wiki", chapter, e.Name()))
			fmt.Fprintf(&b, "- [%s — %s](%s)\n", chapter, title, rel)
			linked++
		}
	}
	if linked == 0 {
		b.WriteString("_No wiki chapters yet — run `kaioken wiki` to generate them._\n")
	}
	b.WriteString("\n")

	// 3. Module map — one line per knowledge card, from its overview.
	b.WriteString("## Module map\n\n")
	modules := cardModules(repo)
	if len(modules) == 0 {
		b.WriteString("_No knowledge cards yet — run `kaioken generate`._\n\n")
	} else {
		for _, m := range modules {
			fmt.Fprintf(&b, "- **%s** — %s\n", m.id, m.summary)
		}
		b.WriteString("\n")
	}

	// 4. Stack — what the scanner saw.
	res, err := scan.Repo(repo, cfg)
	if err != nil {
		return "", err
	}
	b.WriteString("## Stack\n\n")
	fmt.Fprintf(&b, "%s\n\n", res.Stats())
	if len(res.Manifests) > 0 {
		b.WriteString("Manifests: " + strings.Join(res.Manifests, ", ") + "\n\n")
	}

	// 5. Task guides — the skills an agent (or a human) can follow.
	all, err := skills.List(repo)
	if err == nil && len(all) > 0 {
		b.WriteString("## Task guides\n\n")
		for _, sk := range all {
			desc := sk.Description
			if desc == "" {
				desc = "(no description)"
			}
			fmt.Fprintf(&b, "- `%s` — %s\n", sk.Name, desc)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Getting help\n\n" +
		"- `kaioken serve` — browse the full wiki in a browser\n" +
		"- `kaioken status` — see which knowledge is up to date\n" +
		"- the TUI's `read_knowledge` tool answers subsystem questions from this base\n")
	return b.String(), nil
}

// readIntro returns the wiki README's opening text, capped, or "" when there
// is no README.
func readIntro(wikiDir string) string {
	raw, err := os.ReadFile(filepath.Join(wikiDir, "README.md"))
	if err != nil {
		return ""
	}
	text := strings.TrimSpace(string(raw))
	// Drop the markdown title line — the onboarding doc has its own.
	if strings.HasPrefix(text, "# ") {
		if i := strings.IndexByte(text, '\n'); i >= 0 {
			text = strings.TrimSpace(text[i+1:])
		}
	}
	if r := []rune(text); len(r) > maxIntroRunes {
		text = string(r[:maxIntroRunes]) + "…"
	}
	return text
}

type cardModule struct {
	id      string
	summary string
}

// cardModules walks the knowledge-card tree and returns every module with the
// first sentence of its overview card, sorted by module id.
func cardModules(repo string) []cardModule {
	root := filepath.Join(repo, config.Dir, "knowledge")
	var out []cardModule
	filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || d.Name() != "overview.md" {
			return nil
		}
		rel, rerr := filepath.Rel(root, filepath.Dir(path))
		if rerr != nil {
			return nil
		}
		raw, rerr := os.ReadFile(path)
		if rerr != nil {
			return nil
		}
		out = append(out, cardModule{
			id:      filepath.ToSlash(rel),
			summary: firstSentence(strings.TrimSpace(string(raw))),
		})
		return nil
	})
	sort.Slice(out, func(i, j int) bool { return out[i].id < out[j].id })
	return out
}

// firstSentence cuts a card's overview down to its opening sentence.
func firstSentence(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	for _, stop := range []string{". ", "! ", "? "} {
		if i := strings.Index(s, stop); i >= 0 {
			return strings.TrimSpace(s[:i+1])
		}
	}
	if len(s) > 200 {
		return strings.TrimSpace(s[:200]) + "…"
	}
	return strings.TrimSpace(s)
}
