package export

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixture builds a temp repo with a module plan, cards, a wiki with
// provenance footers, an architecture brief and one skill.
func fixture(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	write := func(rel, content string) {
		t.Helper()
		p := filepath.Join(repo, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write(".kaioken/modules.yaml", `version: 1
modules:
  - id: core
    title: Core Engine
    description: the engine
    scope: [core]
  - id: web
    title: Web Layer
    description: http handlers
    scope: [web]
`)
	write(".kaioken/knowledge/core/overview.md", "Core does the work.\n")
	write(".kaioken/knowledge/core/architecture.md", "Pipeline of three stages.\n")
	write(".kaioken/knowledge/core/conventions.md", "- keep stages pure\n")
	write(".kaioken/knowledge/core/tech_stack.md", "Go stdlib only.\n")
	write(".kaioken/knowledge/core/setup_commands.md", "go test ./core/...\n")
	write(".kaioken/knowledge/web/overview.md", "Web serves the engine.\n")
	write(".kaioken/knowledge/web/architecture.md", "One mux, three handlers.\n")
	write(".kaioken/knowledge/web/conventions.md", "- handlers stay thin\n")
	write(".kaioken/knowledge/web/tech_stack.md", "net/http.\n")

	write(".kaioken/wiki_plan.yaml", `version: 1
multiplier: 3
sections:
  - id: arch
    title: Architecture
    goal: explain the system
    files: [core]
`)
	write(".kaioken/wiki/Architecture/Architecture.md",
		"# Architecture\n\nThe big picture.\n\n<!-- kaioken:files core/a.go,core/b.go -->\n")
	write(".kaioken/wiki/Architecture/Stages.md",
		"# Stages\n\nStage detail.\n\n<!-- kaioken:files core/a.go -->\n")

	write(".kaioken/architecture.md",
		"<!-- kaioken architecture brief — instructions -->\n\nA two-part system: core and web.\n")
	write(".kaioken/skills/add-endpoint/SKILL.md",
		"---\nname: add-endpoint\ndescription: how to add an endpoint\n---\nsteps\n")
	return repo
}

func TestExportClaudeMD(t *testing.T) {
	repo := fixture(t)
	out, err := Run(repo, "claude-md", Options{})
	if err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	body := string(raw)

	for _, want := range []string{
		"generated by `kaioken export claude-md`",
		"A two-part system: core and web.", // brief, header comment stripped
		"### Core Engine (`core`)",
		"Pipeline of three stages.",
		"go test ./core/...",
		"### Web Layer (`web`)",
		"- [Architecture](.kaioken/wiki/Architecture/Architecture.md)",
		"- [Architecture / Stages](.kaioken/wiki/Architecture/Stages.md)",
		"**add-endpoint**",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("claude-md missing %q", want)
		}
	}
	if strings.Contains(body, "kaioken architecture brief") {
		t.Error("brief header comment leaked into the export")
	}
	// Core must come before Web (plan order), Architecture card present.
	if strings.Index(body, "Core Engine") > strings.Index(body, "Web Layer") {
		t.Error("modules not in plan order")
	}
}

func TestExportFullInlinesWikiAndStripsProvenance(t *testing.T) {
	repo := fixture(t)
	out, err := Run(repo, "context-md", Options{Full: true})
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := os.ReadFile(out)
	body := string(raw)
	if !strings.Contains(body, "The big picture.") || !strings.Contains(body, "Stage detail.") {
		t.Error("full export did not inline wiki chapters")
	}
	if strings.Contains(body, "kaioken:files") {
		t.Error("provenance footer leaked into the export")
	}
	if filepath.Base(out) != "CONTEXT.md" {
		t.Errorf("context-md wrote %s", out)
	}
}

func TestExportAgentsMDAndCursorRules(t *testing.T) {
	repo := fixture(t)

	out, err := Run(repo, "agents-md", Options{})
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := os.ReadFile(out)
	if !strings.Contains(string(raw), "# AGENTS.md") ||
		!strings.Contains(string(raw), "add-endpoint") {
		t.Error("agents-md missing framing or skills catalog")
	}

	out, err = Run(repo, "cursor-rules", Options{})
	if err != nil {
		t.Fatal(err)
	}
	raw, _ = os.ReadFile(out)
	body := string(raw)
	if filepath.Base(out) != ".cursorrules" {
		t.Errorf("cursor-rules wrote %s", out)
	}
	if !strings.Contains(body, "- keep stages pure") ||
		!strings.Contains(body, "Tech stack: net/http.") {
		t.Error("cursor-rules missing conventions or tech stack")
	}
}

func TestExportRefusesOverwriteWithoutForce(t *testing.T) {
	repo := fixture(t)
	if _, err := Run(repo, "claude-md", Options{}); err != nil {
		t.Fatal(err)
	}
	if _, err := Run(repo, "claude-md", Options{}); err == nil ||
		!strings.Contains(err.Error(), "-force") {
		t.Errorf("second run without -force: got %v, want overwrite refusal", err)
	}
	if _, err := Run(repo, "claude-md", Options{Force: true}); err != nil {
		t.Errorf("run with -force: %v", err)
	}
}

func TestExportDegradesAndErrors(t *testing.T) {
	// Cards only, no wiki/skills/brief: still exports.
	repo := t.TempDir()
	dir := filepath.Join(repo, ".kaioken", "knowledge", "solo")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(filepath.Join(dir, "overview.md"), []byte("Solo module.\n"), 0o644)
	os.WriteFile(filepath.Join(dir, "architecture.md"), []byte("Flat.\n"), 0o644)
	out, err := Run(repo, "claude-md", Options{})
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := os.ReadFile(out)
	if !strings.Contains(string(raw), "Solo module.") {
		t.Error("directory-walk fallback missed the module")
	}
	if strings.Contains(string(raw), "## Wiki") || strings.Contains(string(raw), "## Skills") {
		t.Error("empty sections should be omitted")
	}

	// Nothing generated at all: a pointed error.
	empty := t.TempDir()
	if _, err := Run(empty, "claude-md", Options{}); err == nil ||
		!strings.Contains(err.Error(), "kaioken generate") {
		t.Errorf("empty repo: got %v, want guidance error", err)
	}

	// Unknown target.
	if _, err := Run(repo, "nope", Options{}); err == nil ||
		!strings.Contains(err.Error(), "unknown export target") {
		t.Errorf("unknown target: got %v", err)
	}
}

func TestExportOutOverride(t *testing.T) {
	repo := fixture(t)
	out, err := Run(repo, "claude-md", Options{Out: "docs/ctx.md"})
	if err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(repo, "docs", "ctx.md")
	if out != want {
		t.Errorf("out = %s, want %s", out, want)
	}
	if _, err := os.Stat(want); err != nil {
		t.Error("override path not written")
	}
}
