package scan

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"kaioken/internal/config"
)

// Risk flagging is the cheap half of repository safety: scan already reads
// every file, so noticing that one of them looks like a private key or a
// committed .env costs nothing extra — and it gives the approval dialog, and
// any human reading `kaioken scan`, a heads-up before that file gets touched.

// Flag kinds.
const (
	FlagSecret      = "secret"
	FlagCredentials = "credentials-file"
	FlagGenerated   = "generated"
	FlagLargeBinary = "large-binary"
)

// Flag is one risk finding on a scanned file.
type Flag struct {
	Path   string `json:"path"`   // repo-relative, slash-separated
	Kind   string `json:"kind"`   // one of the Flag* constants
	Detail string `json:"detail"` // human-readable reason
}

// riskInspectBytes caps how much of a file's content the secret patterns see.
// Secrets live at the top of files in practice, and reading more buys only
// scan time on large sources.
const riskInspectBytes = 64 << 10

// largeBinaryBytes is the size over which a skipped binary file is worth
// mentioning — small icons are noise, multi-megabyte blobs are not.
const largeBinaryBytes = 1 << 20

// secretPatterns are high-signal credential shapes. Each is specific enough
// that a match is almost never a false positive; vague shapes (bare "key =")
// are deliberately excluded.
var secretPatterns = []struct {
	name string
	re   *regexp.Regexp
}{
	{"AWS access key", regexp.MustCompile(`AKIA[0-9A-Z]{16}`)},
	{"private key block", regexp.MustCompile(`-----BEGIN (RSA|OPENSSH|EC) PRIVATE KEY-----`)},
	{"GitHub token", regexp.MustCompile(`ghp_[A-Za-z0-9]{36}`)},
	{"OpenAI-style key", regexp.MustCompile(`sk-[A-Za-z0-9]{20,}`)},
	{"Slack token", regexp.MustCompile(`xox[baprs]-`)},
}

// credentialNames are basenames that are credentials regardless of content.
var credentialNames = map[string]bool{
	".env": true, ".env.local": true, "id_rsa": true, "id_ed25519": true,
	"credentials.json": true,
}

// credentialExts are file extensions that usually carry key material.
var credentialExts = map[string]bool{".pem": true, ".p12": true}

// generatedNames marks files that are build output, not source — worth
// knowing before an agent spends edits on them.
var generatedNames = map[string]bool{
	"package-lock.json": true, "pnpm-lock.yaml": true,
}

// detectRisk returns the flags for one text file. base is the filename, rel
// the repo-relative path, content the loaded bytes (possibly nil when the
// file was too large to read).
func detectRisk(rel, base string, content []byte) []Flag {
	var flags []Flag
	lower := strings.ToLower(base)

	if credentialNames[lower] || credentialExts[strings.ToLower(filepath.Ext(base))] {
		flags = append(flags, Flag{Path: rel, Kind: FlagCredentials,
			Detail: "filename looks like credentials"})
	}
	switch {
	case strings.HasSuffix(lower, ".min.js"), strings.HasSuffix(lower, ".map"),
		strings.HasSuffix(lower, ".pb.go"):
		flags = append(flags, Flag{Path: rel, Kind: FlagGenerated,
			Detail: "generated file — edits belong upstream"})
	case generatedNames[lower]:
		flags = append(flags, Flag{Path: rel, Kind: FlagGenerated,
			Detail: "lockfile — generated by the package manager"})
	}

	if len(content) > 0 {
		inspect := content
		if len(inspect) > riskInspectBytes {
			inspect = inspect[:riskInspectBytes]
		}
		for _, p := range secretPatterns {
			if p.re.Match(inspect) {
				flags = append(flags, Flag{Path: rel, Kind: FlagSecret,
					Detail: "matches " + p.name + " pattern"})
			}
		}
	}
	return flags
}

// binaryRisk flags a skipped binary file when it is large enough to matter.
func binaryRisk(rel string, size int64) []Flag {
	if size <= largeBinaryBytes {
		return nil
	}
	return []Flag{{Path: rel, Kind: FlagLargeBinary,
		Detail: "large binary excluded from scanning"}}
}

// SaveFlags persists the scan's risk findings as .kaioken/risk.json so other
// surfaces — the approval dialog above all — can consult them without
// re-scanning. Kept out of Repo itself: scanning stays pure.
func (r *Result) SaveFlags(repo string) error {
	if err := os.MkdirAll(filepath.Join(repo, config.Dir), 0o755); err != nil {
		return err
	}
	flags := r.Flags
	if flags == nil {
		flags = []Flag{}
	}
	raw, err := json.MarshalIndent(flags, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(repo, config.Dir, "risk.json"), raw, 0o644)
}

// LoadFlags reads a previously saved risk.json; missing file yields no flags.
func LoadFlags(repo string) []Flag {
	raw, err := os.ReadFile(filepath.Join(repo, config.Dir, "risk.json"))
	if err != nil {
		return nil
	}
	var flags []Flag
	if err := json.Unmarshal(raw, &flags); err != nil {
		return nil
	}
	return flags
}
