// Package plan asks the LLM to split a scanned repository into a hierarchical
// module tree with explicit file scopes, and persists it as an editable
// .ainow/modules.yaml — the human-in-the-loop checkpoint before generation.
package plan

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"kaioken/internal/config"
	"kaioken/internal/llm"
	"kaioken/internal/scan"
)

// Module is one knowledge unit: a cohesive part of the codebase that gets its
// own card set. Scope entries are repo-relative files or directory prefixes.
type Module struct {
	ID          string   `yaml:"id" json:"id"`
	Title       string   `yaml:"title" json:"title"`
	Description string   `yaml:"description" json:"description"`
	Scope       []string `yaml:"scope" json:"scope"`
	Children    []Module `yaml:"children,omitempty" json:"children,omitempty"`
}

// Plan is the persisted module tree.
type Plan struct {
	Version int      `yaml:"version"`
	Modules []Module `yaml:"modules"`
}

// FilePath returns the modules.yaml path for a repo.
func FilePath(repo string) string {
	return filepath.Join(repo, config.Dir, "modules.yaml")
}

// Load reads an existing plan.
func Load(repo string) (*Plan, error) {
	raw, err := os.ReadFile(FilePath(repo))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no modules.yaml found — run `kaioken plan` first")
		}
		return nil, err
	}
	var p Plan
	if err := yaml.Unmarshal(raw, &p); err != nil {
		return nil, fmt.Errorf("parsing modules.yaml: %w", err)
	}
	return &p, nil
}

// Save writes the plan with an explanatory header.
func (p *Plan) Save(repo string) error {
	if err := os.MkdirAll(filepath.Join(repo, config.Dir), 0o755); err != nil {
		return err
	}
	raw, err := yaml.Marshal(p)
	if err != nil {
		return err
	}
	header := []byte("# kaioken module plan — generated by `kaioken plan`, EDIT FREELY before\n" +
		"# running `kaioken generate`. Rename modules, adjust scopes, split or merge.\n" +
		"# Scope entries are repo-relative file paths or directory prefixes.\n")
	return os.WriteFile(FilePath(repo), append(header, raw...), 0o644)
}

// Flatten returns all modules in the tree, parents before children, with
// hierarchical ids joined by "/".
func (p *Plan) Flatten() []FlatModule {
	var out []FlatModule
	var walk func(ms []Module, prefix string)
	walk = func(ms []Module, prefix string) {
		for _, m := range ms {
			id := m.ID
			if prefix != "" {
				id = prefix + "/" + m.ID
			}
			out = append(out, FlatModule{ID: id, Module: m})
			walk(m.Children, id)
		}
	}
	walk(p.Modules, "")
	return out
}

// FlatModule pairs a module with its full hierarchical id.
type FlatModule struct {
	ID string
	Module
}

const plannerSystem = `You are a senior software architect. You split a repository into a
hierarchical tree of KNOWLEDGE MODULES. Each module is a cohesive functional area that a
new engineer (or an AI coding agent) would want documented as one unit.

Rules:
- Top level: one module per major deliverable (e.g. backend service, frontend app, shared
  libraries, infrastructure). A small repo may be a single module.
- Children: split large deliverables by functional area (feature groups, router groups,
  page groups) — NOT by technical layer alone. 3–10 files per leaf module is ideal;
  never create a module for a single trivial file.
- Scope: list repo-relative file paths or directory prefixes that belong to the module.
  Prefer directory prefixes when a whole directory belongs. Every important source file
  should be covered by exactly one leaf module; parents cover their own top-level files.
- ids: short snake_case, stable, path-like for children (no slashes inside one id).
- Ignore: lockfiles, build output, assets.

Return ONLY a JSON object:
{"modules":[{"id":"...","title":"...","description":"one sentence","scope":["..."],
"children":[...]}]}`

// Generate scans nothing itself — it takes an existing scan result, asks the
// model for a module tree, validates scopes, and returns the plan.
func Generate(ctx context.Context, client *llm.Client, cfg *config.Config, res *scan.Result) (*Plan, error) {
	var user strings.Builder
	user.WriteString("Repository layout (dir → file count, sample files):\n\n")
	user.WriteString(res.TreeSummary(12))
	user.WriteString("\n\nKey manifest/config file contents:\n\n")
	user.WriteString(res.ManifestContents(4000))
	if len(cfg.Notes) > 0 {
		user.WriteString("\nProject steering notes from the maintainer (authoritative):\n")
		for _, n := range cfg.Notes {
			user.WriteString("- " + n + "\n")
		}
	}

	var out struct {
		Modules []Module `json:"modules"`
	}
	if err := client.ChatJSON(ctx, plannerSystem, user.String(), &out); err != nil {
		return nil, fmt.Errorf("planning modules: %w", err)
	}
	if len(out.Modules) == 0 {
		return nil, fmt.Errorf("model returned an empty module list")
	}
	p := &Plan{Version: 1, Modules: out.Modules}
	warnings := Validate(p, res)
	for _, w := range warnings {
		fmt.Fprintln(os.Stderr, "warn:", w)
	}
	return p, nil
}

// Validate checks that scope entries actually match scanned files and returns
// human-readable warnings (it never fails hard — the plan is user-editable).
func Validate(p *Plan, res *scan.Result) []string {
	known := make(map[string]bool, len(res.Files))
	for _, f := range res.Files {
		known[f.Path] = true
	}
	var warnings []string
	for _, fm := range p.Flatten() {
		for _, s := range fm.Scope {
			s = strings.Trim(filepath.ToSlash(s), "/")
			if known[s] {
				continue
			}
			// directory prefix?
			matched := false
			for path := range known {
				if strings.HasPrefix(path, s+"/") {
					matched = true
					break
				}
			}
			if !matched {
				warnings = append(warnings,
					fmt.Sprintf("module %q: scope entry %q matches no scanned file", fm.ID, s))
			}
		}
	}
	return warnings
}

// FilesFor resolves a module's scope entries against the scan result,
// returning the matching files (deduplicated, in scan order).
func FilesFor(m FlatModule, res *scan.Result) []scan.File {
	var out []scan.File
	seen := map[string]bool{}
	for _, s := range m.Scope {
		s = strings.Trim(filepath.ToSlash(s), "/")
		for _, f := range res.Files {
			if f.Path == s || strings.HasPrefix(f.Path, s+"/") {
				if !seen[f.Path] {
					seen[f.Path] = true
					out = append(out, f)
				}
			}
		}
	}
	return out
}
