// Package export flattens Kaioken's generated knowledge — cards, wiki and
// skills under .kaioken/ — into the context-file formats other AI tools read:
// CLAUDE.md, AGENTS.md, .cursorrules, CONTEXT.md. It is pure assembly: no LLM
// calls, no cost, deterministic output from what generation already wrote.
package export

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"kaioken/internal/config"
	"kaioken/internal/plan"
	"kaioken/internal/skills"
	"kaioken/internal/wiki"
)

// Target names one export format.
type Target struct {
	Name    string // the positional argument to `kaioken export`
	Default string // default output path, relative to the repo root
	Desc    string // one line for the target listing
}

// Targets lists the supported formats, in listing order.
func Targets() []Target {
	return []Target{
		{"claude-md", "CLAUDE.md", "single context file for Claude Code (cards + wiki index)"},
		{"agents-md", "AGENTS.md", "agent instruction file: cards + skills catalog"},
		{"cursor-rules", ".cursorrules", "Cursor rules file: conventions + architecture"},
		{"context-md", "CONTEXT.md", "universal context file (same content as claude-md)"},
	}
}

func target(name string) (Target, bool) {
	for _, t := range Targets() {
		if t.Name == name {
			return t, true
		}
	}
	return Target{}, false
}

// Options controls one export run.
type Options struct {
	// Out overrides the target's default output path (repo-relative or absolute).
	Out string
	// Force overwrites an existing output file.
	Force bool
	// Full inlines the wiki chapters instead of listing them, for the
	// markdown targets that carry a wiki section.
	Full bool
}

// moduleCards is one module's generated card set, as found on disk.
type moduleCards struct {
	ID       string
	Title    string
	Overview string
	Arch     string
	Conv     string
	Stack    string
	Setup    string
}

// Run writes one export target and returns the output path it wrote.
func Run(repo, targetName string, opts Options) (string, error) {
	t, ok := target(targetName)
	if !ok {
		return "", fmt.Errorf("unknown export target %q — one of: %s", targetName, targetNames())
	}

	mods := loadCards(repo)
	outline, _ := wiki.LoadOutline(repo)
	if len(mods) == 0 && (outline == nil || len(outline.Sections) == 0) {
		return "", fmt.Errorf("no generated knowledge in %s — run `kaioken generate` (cards) or `kaioken wiki` first", config.Dir)
	}

	var body string
	switch t.Name {
	case "claude-md", "context-md":
		body = renderContext(repo, t.Name, mods, outline, opts.Full)
	case "agents-md":
		body = renderAgents(repo, mods, outline)
	case "cursor-rules":
		body = renderCursorRules(repo, mods)
	}

	out := opts.Out
	if out == "" {
		out = t.Default
	}
	if !filepath.IsAbs(out) {
		out = filepath.Join(repo, out)
	}
	if _, err := os.Stat(out); err == nil && !opts.Force {
		return "", fmt.Errorf("%s already exists — pass -force to overwrite it", out)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(out, []byte(body), 0o644); err != nil {
		return "", err
	}
	return out, nil
}

func targetNames() string {
	names := make([]string, 0, len(Targets()))
	for _, t := range Targets() {
		names = append(names, t.Name)
	}
	return strings.Join(names, ", ")
}

// header opens every export so a reader (and a later run) knows the file is
// generated and how to refresh it.
func header(targetName string) string {
	return fmt.Sprintf("<!-- generated by `kaioken export %s` on %s — regenerate rather than editing -->\n\n",
		targetName, time.Now().UTC().Format("2006-01-02"))
}

// repoName is the human name of the repository being exported.
func repoName(repo string) string {
	abs, err := filepath.Abs(repo)
	if err != nil {
		return filepath.Base(repo)
	}
	return filepath.Base(abs)
}

// ---- content collection ----

// loadCards reads every module's generated cards, ordered by the module plan
// when one exists, falling back to a directory walk of knowledge/ otherwise.
func loadCards(repo string) []moduleCards {
	root := filepath.Join(repo, config.Dir, "knowledge")

	var ids []string
	titles := map[string]string{}
	if p, err := plan.Load(repo); err == nil {
		for _, fm := range p.Flatten() {
			ids = append(ids, fm.ID)
			titles[fm.ID] = fm.Title
		}
	} else {
		ids = walkCardDirs(root)
		sort.Strings(ids)
	}

	var out []moduleCards
	for _, id := range ids {
		dir := filepath.Join(root, filepath.FromSlash(id))
		mc := moduleCards{
			ID:       id,
			Title:    titles[id],
			Overview: readCard(dir, "overview.md"),
			Arch:     readCard(dir, "architecture.md"),
			Conv:     readCard(dir, "conventions.md"),
			Stack:    readCard(dir, "tech_stack.md"),
			Setup:    readCard(dir, "setup_commands.md"),
		}
		if mc.Overview == "" && mc.Arch == "" {
			continue // planned but never generated
		}
		if mc.Title == "" {
			mc.Title = moduleTitle(dir, id)
		}
		out = append(out, mc)
	}
	return out
}

// walkCardDirs finds module ids by looking for card files under knowledge/,
// used when modules.yaml is missing but cards survive on disk.
func walkCardDirs(root string) []string {
	var ids []string
	_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || d.Name() != "overview.md" {
			return nil
		}
		if rel, err := filepath.Rel(root, filepath.Dir(path)); err == nil {
			ids = append(ids, filepath.ToSlash(rel))
		}
		return nil
	})
	return ids
}

func readCard(dir, name string) string {
	raw, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(raw))
}

// moduleTitle recovers a display title from _module.yaml, falling back to the id.
func moduleTitle(dir, id string) string {
	raw, err := os.ReadFile(filepath.Join(dir, "_module.yaml"))
	if err == nil {
		var meta struct {
			Title string `yaml:"title"`
		}
		if yaml.Unmarshal(raw, &meta) == nil && strings.TrimSpace(meta.Title) != "" {
			return meta.Title
		}
	}
	return id
}

// brief returns the architecture brief without its editing-instructions
// header comment, or "" when none was generated.
func brief(repo string) string {
	raw, err := os.ReadFile(wiki.BriefPath(repo))
	if err != nil {
		return ""
	}
	s := string(raw)
	// The brief opens with one HTML comment of maintenance instructions.
	if strings.HasPrefix(s, "<!--") {
		if end := strings.Index(s, "-->"); end >= 0 {
			s = s[end+len("-->"):]
		}
	}
	return strings.TrimSpace(s)
}

// wikiDoc is one generated chapter: its repo-relative path and title.
type wikiDoc struct {
	RelPath string
	Title   string
}

// wikiDocs lists a generated wiki's documents in outline order: each
// section's main document first, then its subsection documents.
func wikiDocs(repo string, outline *wiki.Outline) []wikiDoc {
	if outline == nil {
		return nil
	}
	var docs []wikiDoc
	for _, sec := range outline.Sections {
		dir := wiki.SafeName(sec.Title)
		absDir := filepath.Join(wiki.WikiDir(repo), dir)
		mainName := dir + ".md"
		if _, err := os.Stat(filepath.Join(absDir, mainName)); err == nil {
			docs = append(docs, wikiDoc{
				RelPath: path(config.Dir, "wiki", dir, mainName),
				Title:   sec.Title,
			})
		}
		entries, err := os.ReadDir(absDir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			name := e.Name()
			if e.IsDir() || !strings.HasSuffix(name, ".md") || name == mainName {
				continue
			}
			docs = append(docs, wikiDoc{
				RelPath: path(config.Dir, "wiki", dir, name),
				Title:   sec.Title + " / " + strings.TrimSuffix(name, ".md"),
			})
		}
	}
	return docs
}

func path(parts ...string) string { return strings.Join(parts, "/") }

// ---- renderers ----

// renderContext produces the claude-md / context-md body: brief, cards, wiki.
func renderContext(repo, targetName string, mods []moduleCards, outline *wiki.Outline, full bool) string {
	var b strings.Builder
	b.WriteString(header(targetName))
	fmt.Fprintf(&b, "# %s — Project Context\n\n", repoName(repo))
	b.WriteString("Dense, generated context for AI coding tools: architecture, per-module\n")
	b.WriteString("knowledge and conventions extracted from the actual source.\n\n")

	if br := brief(repo); br != "" {
		b.WriteString("## Architecture Brief\n\n" + br + "\n\n")
	}

	writeModuleCards(&b, mods, true)

	if docs := wikiDocs(repo, outline); len(docs) > 0 {
		b.WriteString("## Wiki\n\n")
		if full {
			for _, d := range docs {
				raw, err := os.ReadFile(filepath.Join(repo, filepath.FromSlash(d.RelPath)))
				if err != nil {
					continue
				}
				fmt.Fprintf(&b, "<!-- %s -->\n\n", d.RelPath)
				b.WriteString(strings.TrimSpace(wiki.StripProvenance(string(raw))) + "\n\n---\n\n")
			}
		} else {
			b.WriteString("Deeper chapters live in the generated wiki — read them on demand:\n\n")
			for _, d := range docs {
				fmt.Fprintf(&b, "- [%s](%s)\n", d.Title, d.RelPath)
			}
			b.WriteString("\n")
		}
	}

	writeSkillsCatalog(&b, repo)
	return b.String()
}

// renderAgents produces the AGENTS.md body: instructions-first framing, the
// same cards, and the skills catalog agents are expected to load.
func renderAgents(repo string, mods []moduleCards, outline *wiki.Outline) string {
	var b strings.Builder
	b.WriteString(header("agents-md"))
	b.WriteString("# AGENTS.md\n\n")
	fmt.Fprintf(&b, "Instructions for AI agents working in %s. Generated from the code by\n", repoName(repo))
	b.WriteString("Kaioken — follow the conventions below; they are observed patterns, not aspirations.\n\n")

	if br := brief(repo); br != "" {
		b.WriteString("## Architecture\n\n" + br + "\n\n")
	}

	writeModuleCards(&b, mods, false)

	if docs := wikiDocs(repo, outline); len(docs) > 0 {
		b.WriteString("## Deeper Documentation\n\n")
		for _, d := range docs {
			fmt.Fprintf(&b, "- [%s](%s)\n", d.Title, d.RelPath)
		}
		b.WriteString("\n")
	}

	writeSkillsCatalog(&b, repo)
	return b.String()
}

// renderCursorRules produces the .cursorrules body: prose rules, no link
// scaffolding — Cursor injects the file verbatim as steering text.
func renderCursorRules(repo string, mods []moduleCards) string {
	var b strings.Builder
	b.WriteString(header("cursor-rules"))
	fmt.Fprintf(&b, "# Rules for %s\n\n", repoName(repo))
	b.WriteString("Generated from the codebase by Kaioken. These are observed conventions —\n")
	b.WriteString("match them in every change.\n\n")

	if br := brief(repo); br != "" {
		b.WriteString("## Architecture\n\n" + br + "\n\n")
	}

	for _, m := range mods {
		fmt.Fprintf(&b, "## %s (`%s`)\n\n", m.Title, m.ID)
		if m.Overview != "" {
			b.WriteString(m.Overview + "\n\n")
		}
		if m.Stack != "" {
			b.WriteString("Tech stack: " + m.Stack + "\n\n")
		}
		if m.Conv != "" {
			b.WriteString("Conventions:\n\n" + m.Conv + "\n\n")
		}
	}
	return b.String()
}

// writeModuleCards renders every module's cards. withStack controls whether
// the tech-stack card is included (agents-md leans on conventions instead).
func writeModuleCards(b *strings.Builder, mods []moduleCards, withStack bool) {
	if len(mods) == 0 {
		return
	}
	b.WriteString("## Modules\n\n")
	for _, m := range mods {
		fmt.Fprintf(b, "### %s (`%s`)\n\n", m.Title, m.ID)
		if m.Overview != "" {
			b.WriteString(m.Overview + "\n\n")
		}
		if m.Arch != "" {
			b.WriteString("**Architecture**\n\n" + m.Arch + "\n\n")
		}
		if m.Conv != "" {
			b.WriteString("**Conventions**\n\n" + m.Conv + "\n\n")
		}
		if withStack && m.Stack != "" {
			b.WriteString("**Tech stack**: " + m.Stack + "\n\n")
		}
		if m.Setup != "" {
			b.WriteString("**Setup / test commands**\n\n" + m.Setup + "\n\n")
		}
	}
}

// writeSkillsCatalog appends the generated skills as a load-on-demand list.
func writeSkillsCatalog(b *strings.Builder, repo string) {
	all, err := skills.List(repo)
	if err != nil || len(all) == 0 {
		return
	}
	b.WriteString("## Skills\n\n")
	b.WriteString("Task-oriented guides generated for this repo — load the relevant one before starting:\n\n")
	for _, s := range all {
		fmt.Fprintf(b, "- **%s** — %s (`%s`)\n", s.Name, s.Description,
			path(config.Dir, "skills", s.Name, "SKILL.md"))
	}
	b.WriteString("\n")
}
